# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Quicklisp
        id: cache-ql
        uses: actions/cache@v2
        with:
          path: ~/quicklisp/
          key: ${{ runner.os }}-ql

      - name: Install SBCL
        if: steps.cache-sbcl.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install sbcl
          sbcl --version
      - name: Install Quicklisp
        if: steps.cache-ql.outputs.cache-hit != 'true'
        run: |
          curl -o $HOME/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
          sbcl --noinform --end-runtime-options --no-sysinit --no-userinit --disable-debugger --load "$HOME/quicklisp.lisp" --eval "(quicklisp-quickstart:install)" --quit
      - name: Unit Tests
        shell: bash
        run: |
          chmod +x $GITHUB_WORKSPACE/test.sh
          $GITHUB_WORKSPACE/test.sh
