# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBCL
        id: cache-sbcl
        uses: actions/cache@v2
        with:
          path: ~/sbcl/
          key: ${{ runner.os }}-sbcl
      - name: Cache Quicklisp
        id: cache-ql
        uses: actions/cache@v2
        with:
          path: ~/quicklisp/
          key: ${{ runner.os }}-sbcl        
    
      - name: Configure SBCL
        run: |
          echo "SBCL_HOME=$HOME\sbcl\" >> $GITHUB_ENV
          echo "$HOME\sbcl\" >> $GITHUB_PATH
      - name: Install SBCL
        if: steps.cache-sbcl.outputs.cache-hit != 'true'
        run: |
          mkdir -p "$SBCL_HOME" ** \
              curl https://pilotfiber.dl.sourceforge.net/project/sbcl/sbcl/2.1.0/sbcl-2.1.0-x86-64-linux-binary.tar.bz2 -s -o - | \
              tar jxvf - -C $SBCL_HOME
      - name: Install Quicklisp
        if: steps.cache-ql.outputs.cache-hit != 'true'
        run: |
          curl -o $TEMP/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
          sbcl --noinform --end-runtime-options --no-sysinit --no-userinit --disable-debugger --load "$TEMP\quicklisp.lisp" --eval "(quicklisp-quickstart:install)" --quit
      - name: Unit Tests
        shell: bash
        run: ./test.sh
